// This file is generated by scripts/generate-version.mjs (runs as prebuild).
// Do not edit by hand — regenerate via `pnpm --filter @tatlacas/brevwick-react-native build`
// or `node scripts/generate-version.mjs`.

/**
 * Semantic version of the installed `@tatlacas/brevwick-react-native` package.
 *
 * The string literal is written at build time by `scripts/generate-version.mjs`
 * from `package.json#version`. Metro resolves this package via the
 * top-level `react-native` field (`./src/index.ts`) and does not perform
 * define-style substitution, so we cannot rely on an ambient token: the
 * literal must already be in the source the bundler reads.
 */
export const BREVWICK_REACT_NATIVE_VERSION: string = '1.0.1-beta.0';
