// This file is generated by scripts/generate-version.mjs (runs as prebuild).
// Do not edit by hand — regenerate via `pnpm --filter @tatlacas/brevwick-angular build`
// or `node scripts/generate-version.mjs`.

/**
 * Semantic version of the installed `@tatlacas/brevwick-angular` package.
 *
 * The string literal is written at build time by `scripts/generate-version.mjs`
 * from `package.json#version`. ng-packagr does not perform define-style
 * substitution, so we cannot rely on an ambient token: the literal must
 * already be in the source the bundler reads.
 */
export const BREVWICK_ANGULAR_VERSION: string = '1.0.0-beta.13';
