// This file is generated by scripts/generate-version.mjs (runs as prebuild).
// Do not edit by hand — regenerate via `pnpm --filter @tatlacas/brevwick-svelte build`
// or `node scripts/generate-version.mjs`.

/**
 * Semantic version of the installed `@tatlacas/brevwick-svelte` package.
 *
 * The string literal is written at build time by `scripts/generate-version.mjs`
 * from `package.json#version`. `svelte-package` does not perform define-style
 * substitution, so we cannot rely on an ambient token: the literal must
 * already be in the source the bundler reads.
 */
export const BREVWICK_SVELTE_VERSION: string = '2.0.0-beta.1';
