#!/usr/bin/env node
/**
 * Build-time codegen for `src/lib/internal/version.ts`.
 *
 * Why: `svelte-package` does not run a `define`-style substitution pass, so
 * an ambient `__BREVWICK_SVELTE_VERSION__` token survives into the published
 * dist and crashes consumers with `ReferenceError`. Instead of relying on a
 * build plugin, we write the literal version string into source as a
 * `prebuild` step — same pattern the Angular + React-Native adapters use
 * for their version exports.
 *
 * Idempotent: only writes when the file content would change, so a clean
 * `git status` after `pnpm build` is preserved when the version is in sync.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(here, '..', 'package.json');
const targetPath = resolve(here, '..', 'src', 'lib', 'internal', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = String(pkg.version ?? '');

if (!version) {
  console.error(
    '[generate-version] package.json is missing a version field — aborting.',
  );
  process.exit(1);
}

const banner = `// This file is generated by scripts/generate-version.mjs (runs as prebuild).
// Do not edit by hand — regenerate via \`pnpm --filter @tatlacas/brevwick-svelte build\`
// or \`node scripts/generate-version.mjs\`.
`;

// Match the project's Prettier config (single quotes for TS) so a
// regenerated `version.ts` does not show up as a `format:check` diff in CI.
const literal = `'${version.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const body = `/**
 * Semantic version of the installed \`@tatlacas/brevwick-svelte\` package.
 *
 * The string literal is written at build time by \`scripts/generate-version.mjs\`
 * from \`package.json#version\`. \`svelte-package\` does not perform define-style
 * substitution, so we cannot rely on an ambient token: the literal must
 * already be in the source the bundler reads.
 */
export const BREVWICK_SVELTE_VERSION: string = ${literal};
`;

const next = `${banner}\n${body}`;

let current = '';
try {
  current = readFileSync(targetPath, 'utf8');
} catch {
  // First-run case (file does not exist yet) — leave `current` empty so the
  // following diff treats it as out-of-date and writes the generated body.
}

if (current === next) {
  // Idempotent: avoid touching mtime when content is already correct.
  process.exit(0);
}

writeFileSync(targetPath, next, 'utf8');
console.log(`[generate-version] wrote ${targetPath} (version=${version})`);
