#!/usr/bin/env node
/**
 * Build-time codegen for `src/internal/version.ts`.
 *
 * Why: this package's `exports["."]` declares a `"solid"` condition that
 * resolves to `./src/index.ts` so Solid-aware bundlers (vite-plugin-solid /
 * SolidStart) can compile the JSX with their own toolchain. That source
 * path skips tsup's `define` pass entirely, so an ambient
 * `__BREVWICK_SOLID_VERSION__` token survives into the consumer's bundle
 * and crashes with `ReferenceError`. Writing the literal version string
 * into source as a `prebuild` step matches the pattern the Angular,
 * React-Native, and Svelte adapters use.
 *
 * Idempotent: only writes when the file content would change, so a clean
 * `git status` after `pnpm build` is preserved when the version is in sync.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(here, '..', 'package.json');
const targetPath = resolve(here, '..', 'src', 'internal', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = String(pkg.version ?? '');

if (!version) {
  console.error(
    '[generate-version] package.json is missing a version field — aborting.',
  );
  process.exit(1);
}

const banner = `// This file is generated by scripts/generate-version.mjs (runs as prebuild).
// Do not edit by hand — regenerate via \`pnpm --filter @tatlacas/brevwick-solid build\`
// or \`node scripts/generate-version.mjs\`.
`;

const literal = `'${version.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const body = `/**
 * Semantic version of the installed \`@tatlacas/brevwick-solid\` package.
 *
 * The string literal is written at build time by \`scripts/generate-version.mjs\`
 * from \`package.json#version\`. The package's \`"solid"\` export condition
 * points at this source file so vite-plugin-solid / SolidStart compile JSX
 * with their own toolchain — that path bypasses tsup's \`define\` pass, so
 * the literal must already be in the source the bundler reads.
 */
export const BREVWICK_SOLID_VERSION: string = ${literal};
`;

const next = `${banner}\n${body}`;

let current = '';
try {
  current = readFileSync(targetPath, 'utf8');
} catch {
  // First-run case (file does not exist yet) — leave `current` empty so the
  // following diff treats it as out-of-date and writes the generated body.
}

if (current === next) {
  process.exit(0);
}

writeFileSync(targetPath, next, 'utf8');
console.log(`[generate-version] wrote ${targetPath} (version=${version})`);
