import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      // Unit tests run under jsdom; route every `react-native` import to a
      // local stub so import-time evaluation in feature worktrees does not
      // depend on a Metro bundler or device. The stub lives under `test/`
      // (not `src/`) so it never ships in the published npm tarball.
      // Richer mocks land alongside the feature work that needs them.
      'react-native': fileURLToPath(
        new URL('./test/__mocks__/react-native.ts', import.meta.url),
      ),
    },
  },
  test: {
    environment: 'jsdom',
    include: ['src/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/index.ts',
        // Generated by `scripts/generate-version.mjs` — single-literal
        // module, not product logic.
        'src/version.ts',
      ],
      // Floor, not target — mirrors `packages/react/vitest.config.ts` so
      // a contributor who forgets to write tests cannot slip through.
      // Set when #87 (route ring) shipped the first real test code in
      // this package; #83's provider work will tighten further.
      thresholds: {
        lines: 75,
        statements: 75,
        functions: 75,
        branches: 70,
      },
    },
  },
});
