// This file is generated by scripts/generate-version.mjs (runs as prebuild).
// Do not edit by hand — regenerate via `pnpm --filter @tatlacas/brevwick-solid build`
// or `node scripts/generate-version.mjs`.

/**
 * Semantic version of the installed `@tatlacas/brevwick-solid` package.
 *
 * The string literal is written at build time by `scripts/generate-version.mjs`
 * from `package.json#version`. The package's `"solid"` export condition
 * points at this source file so vite-plugin-solid / SolidStart compile JSX
 * with their own toolchain — that path bypasses tsup's `define` pass, so
 * the literal must already be in the source the bundler reads.
 */
export const BREVWICK_SOLID_VERSION: string = '1.0.1-beta.0';
